name: TikTok Scheduler

on:
  schedule:
    - cron: '0 * * * *'  # run every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  tiktok-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f $GITHUB_WORKSPACE/requirements.txt ]; then
            pip install -r $GITHUB_WORKSPACE/requirements.txt
          else
            echo "No requirements.txt found, skipping installation"
          fi

      - name: Run TikTok Scheduler
        run: |
          python your_tiktok_script.py
