name: TikTok Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

jobs:
  run-tiktok:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run TikTok scheduler
        env:
          TIKTOK_API_TOKEN: ggmm9eolNAOM38Zr   # your free trial token
        run: |
          python your_tiktok_script.py

          python tiktok_post_scheduler.py
